name = "PEtab"
uuid = "48d54b35-e43e-4a66-a5a1-dde6b987cf69"
authors = ["Viktor Hasselgren", "Sebastian Persson", "Rafael Arutjunjan", "Damiano Ognissanti"]
version = "2.13.0"

[deps]
ArrayInterface = "4fba245c-0d91-5ea0-9b3e-6abc04ee57a9"
Bijectors = "76274a88-744f-5084-9051-94815aaf08c4"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Catalyst = "479239e8-5488-4da2-87a7-35f2df7eef83"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LogDensityProblems = "6fdf6af0-433a-55f7-b3ed-c6c6e0b8df7c"
LogDensityProblemsAD = "996a588d-648d-4e1f-a8f0-a84b347e47b1"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
PreallocationTools = "d236fae5-4411-538c-8e31-a6e3d9e00b46"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
QuasiMonteCarlo = "8a4e6c94-4038-4cdc-81c3-7e6ffdb2a71b"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"
RuntimeGeneratedFunctions = "7e49a35a-f44a-4d26-94aa-eba1b4ca6b47"
SBMLImporter = "210efffb-c3c8-456d-a807-6f55560b12fe"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
SteadyStateDiffEq = "9672c7b4-1e72-59bd-8a11-6ac3964bc41f"
Sundials = "c3572dad-4567-51f8-b174-8c6c989267f4"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[weakdeps]
Bijectors = "76274a88-744f-5084-9051-94815aaf08c4"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
LogDensityProblems = "6fdf6af0-433a-55f7-b3ed-c6c6e0b8df7c"
LogDensityProblemsAD = "996a588d-648d-4e1f-a8f0-a84b347e47b1"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
SciMLSensitivity = "1ed8b502-d754-442c-8d5d-10ac956f44a1"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[extensions]
PEtabIpoptExtension = ["Ipopt"]
PEtabLogDensityProblemsExtension = ["LogDensityProblems", "LogDensityProblemsAD", "Bijectors"]
PEtabMCMCChainsExtension = ["MCMCChains"]
PEtabOptimExtension = ["Optim"]
PEtabOptimizationExtension = ["Optimization"]
PEtabPlotsExtension = ["Plots"]
PEtabPyCallExtension = ["PyCall"]
PEtabSciMLSensitivityExtension = ["SciMLSensitivity", "Zygote"]

[compat]
AdaptiveMCMC = "0.1.4"
AdvancedHMC = "0.6"
Aqua = "0.8"
ArrayInterface = "7.7"
Bijectors = "0.13"
CSV = "0.10"
Catalyst = "13"
ChainRulesCore = "1"
DataFrames = "1"
DiffEqCallbacks = "2"
Distributions = "0.21 - 0.25"
FiniteDifferences = "0.12"
ForwardDiff = "0.10"
Ipopt = "1"
LinearAlgebra = "1"
LogDensityProblems = "2.1"
LogDensityProblemsAD = "1.7"
MCMCChains = "6"
ModelingToolkit = "8"
NonlinearSolve = "3"
Optim = "1"
Optimization = "3"
OptimizationOptimJL = "0.2"
OrdinaryDiffEq = "6"
Plots = "1"
PreallocationTools = "0.4"
PrecompileTools = "1"
Printf = "1"
PyCall = "1"
QuasiMonteCarlo = "0.3"
Random = "1"
ReverseDiff = "1"
RuntimeGeneratedFunctions = "0.5"
SBMLImporter = "1.0.3"
SafeTestsets = "0.1"
SciMLBase = "2"
SciMLSensitivity = "7.55"
StatsBase = "0.34"
SteadyStateDiffEq = "2"
Sundials = "4"
Test = "1"
YAML = "0.4"
Zygote = "0.6"
julia = "1"

[extras]
AdaptiveMCMC = "717c3277-546c-407d-8270-09a39a0919a0"
AdvancedHMC = "0bf59076-c3b1-5ca4-86bd-e02cd72cde3d"
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Bijectors = "76274a88-744f-5084-9051-94815aaf08c4"
FiniteDifferences = "26cc04aa-876d-5657-8c51-4c34ba976000"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
LogDensityProblems = "6fdf6af0-433a-55f7-b3ed-c6c6e0b8df7c"
LogDensityProblemsAD = "996a588d-648d-4e1f-a8f0-a84b347e47b1"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
SciMLSensitivity = "1ed8b502-d754-442c-8d5d-10ac956f44a1"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[targets]
test = ["Aqua", "Bijectors", "Test", "SafeTestsets", "SciMLSensitivity", "Zygote", "Ipopt", "Optim", "Plots", "Optimization", "OptimizationOptimJL", "FiniteDifferences", "PyCall", "LogDensityProblems", "LogDensityProblemsAD", "AdaptiveMCMC", "AdvancedHMC", "MCMCChains"]
